---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
platforms:
  - name: centos7
    box: centos/7
    memory: 1024
    cpus: 1
    provider_raw_config_args:
    - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    v: true
    sudo: true
  lint:
    name: flake8
